name: Skill Publish
on:
  push:
    tags: ['v*']

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Identify changed skills
        id: changes
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 HEAD^ 2>/dev/null || echo "")
          if [ -z "$PREV_TAG" ]; then
            CHANGED=$(ls -d *-skill/ 2>/dev/null | tr '\n' ' ')
          else
            CHANGED=$(git diff --name-only "$PREV_TAG" HEAD | grep -o '^[^/]*-skill/' | sort -u | tr '\n' ' ')
          fi
          echo "skills=$CHANGED" >> $GITHUB_OUTPUT
      - name: Package skills
        run: |
          mkdir -p dist
          for skill in ${{ steps.changes.outputs.skills }}; do
            skill_name=$(basename "$skill")
            bash pipeline/scripts/package-skill.sh "$skill"
          done
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*.tar.gz
          generate_release_notes: true
